name: yuque-devtools
on: [ push, workflow_dispatch ]
jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: node
        uses: actions/setup-node@master

      - name: run
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: |
          npm i -g hexo-cli
          npm i -g yuque-hexo
          cd devtools
          npm install
          yuque-hexo clean 
          yuque-hexo sync 
          
          cd ../programmingLanguages
          npm install
          yuque-hexo clean
          yuque-hexo sync
          cp -rf source ../devtools     
          
          cd ../systemsAndNetworks
          npm install
          yuque-hexo clean
          yuque-hexo sync
          cp -rf source ../devtools     
                    
          cd ../databasesAndStorage
          npm install
          yuque-hexo clean
          yuque-hexo sync
          cp -rf source ../devtools     
                              
          cd ../securityAndEncryption
          npm install
          yuque-hexo clean
          yuque-hexo sync
          cp -rf source ../devtools     
                                        
          cd ../dataAnalysisAndMachineLearning
          npm install
          yuque-hexo clean
          yuque-hexo sync
          cp -rf source ../devtools     
                                                  
          cd ../designAndUserExperience
          npm install
          yuque-hexo clean
          yuque-hexo sync
          cp -rf source ../devtools     
          
          cd ../devtools
          hexo clean
          hexo g
          cp -rf public ..
          
          echo end

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          external_repository: luolong47/luolong47.github.io
          publish_branch: master
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
